version: "3.9"

services:
  app:
    image: jarebear/picklist:latest
    container_name: picklist_app
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://picklist:picklistpassword@db:5432/picklistdb
    ports:
      - "5061:5061"
    volumes:
      - /mnt/rootshare/PickList:/app/data

  db:
    image: postgres:16
    container_name: picklist_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: picklistdb
      POSTGRES_USER: picklist
      POSTGRES_PASSWORD: picklistpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
